version: '3.8'

services:
    artscure:
        image: kooldev/php:8.1
        container_name: artscure
        working_dir: /artscure
        restart: always
        networks:
            - internal
            - nginx_network
        volumes:
            - '.:/artscure'
            - './docker/php/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
        links:
            - artscure-database
        depends_on:
            - artscure-database
    artscure-nginx:
        image: nginx:alpine
        container_name: artscure-nginx
        restart: always
        working_dir: /artscure
        networks:
            - internal
            - nginx_network
        ports:
            - "9002:80"
        volumes:
            - .:/artscure
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - artscure
    artscure-composer:
        image: composer:latest
        container_name: artscure-composer
        working_dir: /artscure
        command: update --ignore-platform-reqs
        volumes:
            - .:/artscure
        restart: on-failure
        depends_on:
            - artscure
    artscure-database:
        image: mariadb:latest
        restart: always
        container_name: artscure-database
        working_dir: /artscure
        networks:
            - internal
            - nginx_network
        command: mysqld --skip-grant-tables
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=artscure
            - MYSQL_USER=root
            - MYSQL_PASSWORD=password
        volumes:
            - .:/artscure
            - ./artscure-database:/var/lib/mysql
        ports:
            - '8000:3306'
    artscure-redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - artscure-redis:/data
        networks:
            - internal
            - nginx_network
        command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    phpmyadmin:
        depends_on:
            - artscure-database
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_HOST=artscure-database
            - PMA_PORT=3306
        networks:
            - internal
            - nginx_network
        ports:
            - 8001:80

networks:
    nginx_network:
        external: true
    internal:
        driver: overlay
        name: 'global'
        attachable: true
volumes:
    artscure-database:
        driver: local
    artscure-redis:
        driver: local
